version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpgdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
